apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-gke-ing
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: cloud-api-basic-svc
          servicePort: 8080