apiVersion: v1
kind: Namespace
metadata:
  name: fms-app
  labels:
    name: fms-app

# Create the Pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fms-admin-deploy
  namespace: fms-app
  labels:
    app: fms-admin
spec: # for deployment
  replicas: 1
  selector:
    matchLabels:
      app: fms-admin
  template:
    metadata:
      labels:
        app: fms-admin
    spec: # for pod
      containers:
      - name: fms-admin
        image: 1017860556361/fms-admin:v4.2
        resources: 
          limits:
            memory: "2048Mi"  
            cpu: "500m"
          requests:                   # request memory can't greater than limits memory
            memory: "2048Mi"  
            cpu: "300m"
        ports:
         - containerPort: 9090
        env:
          - name: com.fms.uri 
            value: "mongodb://admin:fms135246@10.128.0.7:27017/admin?waitQueueTimeoutMS=180000&maxPoolSize=5000" 
          - name: CATALINA_OPTS 
            value: "-Dcom.fms.cache.address=10.160.0.3:5701 -Dcom.fms.cache.group.name=fms_cache_cloud -Dhazelcast.application.validation.token=fms#123456"     
        volumeMounts:
           - name: fms-build
             mountPath: /usr/etc
      volumes:
           - name: fms-build
             persistentVolumeClaim:
               claimName: fms-pvc

# Create the Internal Service  
# '---' by this syntex can create multile documants in yaml fle 

---    
apiVersion: v1
kind: Service
metadata:
  name: fms-admin-svc
  namespace: fms-app
spec: # for deployment
  selector:
      app: fms-admin
  type: LoadBalancer    
  ports:
     - protocol: TCP
       port: 9090
       targetPort: 9090

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fms-stg-cls
  namespace: fms-app
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
volumeBindingMode: WaitForFirstConsumer    

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fms-pvc
  namespace: fms-app
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: "fms-stg-cls"
